-- Reference schema for the Render/Supabase deployment. Review before applying.
-- The Flask app can also create the tables for a quick local start.

create table if not exists account (id bigserial primary key, username varchar(120) unique not null, password_hash varchar(255) not null, role varchar(20) not null, display_name varchar(160) not null, must_change_password boolean not null default true, active boolean not null default true, created_at timestamp not null default now(), last_login timestamp);
create index if not exists ix_account_role on account(role);
create table if not exists student (id bigserial primary key, admission_number varchar(50) unique not null, roll_number varchar(30), name varchar(160) not null, class_name varchar(10) not null, section varchar(10) not null default '', second_language varchar(30), third_language varchar(30), date_of_birth date, mother_name varchar(160), father_name varchar(160), address text, phone varchar(40), email varchar(160), previous_school varchar(200), active boolean not null default true, account_id bigint unique references account(id), face_encoding_json text, face_trained boolean not null default false, created_at timestamp not null default now());
create index if not exists ix_student_class_section on student(class_name,section);
create table if not exists parent (id bigserial primary key, name varchar(160) not null, phone varchar(40), email varchar(160), account_id bigint unique references account(id));
create table if not exists parent_student (id bigserial primary key, parent_id bigint not null references parent(id) on delete cascade, student_id bigint not null references student(id) on delete cascade, unique(parent_id,student_id));
create table if not exists teacher (id bigserial primary key, name varchar(160) not null, email varchar(160), phone varchar(40), account_id bigint unique references account(id), signature_data text, active boolean not null default true);
create table if not exists teacher_assignment (id bigserial primary key, teacher_id bigint not null references teacher(id) on delete cascade, class_name varchar(10) not null, section varchar(10) not null default '', subject_code varchar(50) not null, unique(teacher_id,class_name,section,subject_code));
create table if not exists subject (id bigserial primary key, code varchar(50) unique not null, name varchar(120) not null, class_band varchar(20) not null, language_group varchar(20), active boolean not null default true);
create table if not exists exam (id bigserial primary key, name varchar(50) unique not null, max_marks integer not null, order_index integer not null, is_final boolean not null default false, active boolean not null default true);
create table if not exists mark (id bigserial primary key, student_id bigint not null references student(id) on delete cascade, subject_code varchar(50) not null, exam_id bigint not null references exam(id) on delete cascade, marks numeric(7,2), max_marks integer not null, updated_by varchar(120), updated_at timestamp not null default now(), locked boolean not null default false, unique(student_id,subject_code,exam_id));
create index if not exists ix_mark_student_exam on mark(student_id,exam_id);
create table if not exists assessment_component (id bigserial primary key, student_id bigint not null references student(id) on delete cascade, subject_code varchar(50) not null, multiple_assessment numeric(6,2) default 0, subject_enrichment numeric(6,2) default 0, portfolio numeric(6,2) default 0, internal_assessment numeric(6,2), annual_exam numeric(6,2), remarks varchar(500), unique(student_id,subject_code));
create table if not exists attendance (id bigserial primary key, student_id bigint not null references student(id) on delete cascade, date date not null, status varchar(20) not null default 'present', time_in time, source varchar(20) not null default 'face', marked_by varchar(120), note varchar(500), unique(student_id,date));
create index if not exists ix_attendance_date_status on attendance(date,status);
create table if not exists school_calendar (id bigserial primary key, date date unique not null, is_working boolean not null default true, reason varchar(255));
create table if not exists announcement (id bigserial primary key, title varchar(180) not null, message text not null, audience varchar(30) not null default 'all', published boolean not null default false, created_by varchar(120) not null, created_at timestamp not null default now(), published_at timestamp);
create table if not exists result_publication (id bigserial primary key, exam_id bigint not null references exam(id) on delete cascade, class_name varchar(10) not null, section varchar(10) not null default '', published boolean not null default false, published_at timestamp, published_by varchar(120), unique(exam_id,class_name,section));
create table if not exists audit_event (id bigserial primary key, occurred_at timestamp not null default now(), actor_username varchar(120) not null, actor_role varchar(30) not null, action varchar(120) not null, target_type varchar(80), target_id varchar(80), ip_address varchar(64), user_agent text, metadata_json text, previous_hash varchar(64), event_hash varchar(64) not null);
create index if not exists ix_audit_event_time on audit_event(occurred_at);
create table if not exists school_setting (id bigserial primary key, key varchar(120) unique not null, value text, updated_at timestamp not null default now());
create table if not exists published_report (id bigserial primary key, student_id bigint not null references student(id) on delete cascade, session_name varchar(30) not null, status varchar(20) not null default 'draft', pdf_path varchar(255), published_at timestamp, published_by varchar(120), unique(student_id,session_name));

insert into exam(name,max_marks,order_index,is_final) values ('PT-1',40,1,false),('PT-2',80,2,false),('PT-3',40,3,false),('Final Examination',80,4,true) on conflict (name) do nothing;

create table if not exists fee_invoice (id bigserial primary key, student_id bigint not null references student(id) on delete cascade, title varchar(160) not null, amount_due numeric(12,2) not null default 0, due_date date, status varchar(20) not null default 'pending', created_at timestamp not null default now());
create index if not exists ix_fee_invoice_student on fee_invoice(student_id);
create table if not exists fee_payment (id bigserial primary key, invoice_id bigint not null references fee_invoice(id) on delete cascade, amount numeric(12,2) not null, method varchar(40) not null default 'offline', receipt_no varchar(80) unique not null, paid_at timestamp not null default now(), received_by varchar(120));
create index if not exists ix_fee_payment_invoice on fee_payment(invoice_id);
