-- V11 compatibility migration for the existing Supabase/Postgres schema.
-- Run this after backing up the database. It preserves existing rows where practical.

CREATE TABLE IF NOT EXISTS public.account (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(120) UNIQUE NOT NULL,
  password_hash varchar(255) NOT NULL,
  role varchar(20) NOT NULL,
  display_name varchar(160) NOT NULL,
  must_change_password boolean NOT NULL DEFAULT true,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT now(),
  last_login timestamp,
  profile_picture_path varchar(255)
);

ALTER TABLE public.account ADD COLUMN IF NOT EXISTS profile_picture_path varchar(255);

ALTER TABLE public.student ADD COLUMN IF NOT EXISTS section varchar(10);
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS second_language varchar(30);
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS third_language varchar(30);
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS date_of_birth date;
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS mother_name varchar(160);
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS father_name varchar(160);
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS phone varchar(40);
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS email varchar(160);
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS previous_school varchar(200);
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS face_encoding_json text;
ALTER TABLE public.student ADD COLUMN IF NOT EXISTS face_trained boolean NOT NULL DEFAULT false;
UPDATE public.student SET section='' WHERE section IS NULL;
ALTER TABLE public.student ALTER COLUMN section SET DEFAULT '';

ALTER TABLE public.teacher ADD COLUMN IF NOT EXISTS email varchar(160);
ALTER TABLE public.teacher ADD COLUMN IF NOT EXISTS phone varchar(40);
ALTER TABLE public.teacher ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE public.teacher ADD COLUMN IF NOT EXISTS signature_data text;
-- Legacy teacher login columns are replaced by account; keep them only for compatibility.
ALTER TABLE public.teacher ALTER COLUMN username DROP NOT NULL;
ALTER TABLE public.teacher ALTER COLUMN password_hash DROP NOT NULL;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='student_account_fk') THEN
    ALTER TABLE public.student ADD CONSTRAINT student_account_fk FOREIGN KEY(account_id) REFERENCES public.account(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='teacher_account_fk') THEN
    ALTER TABLE public.teacher ADD CONSTRAINT teacher_account_fk FOREIGN KEY(account_id) REFERENCES public.account(id);
  END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uq_student_account ON public.student(account_id) WHERE account_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_teacher_account ON public.teacher(account_id) WHERE account_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.parent (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(160) NOT NULL, phone varchar(40), email varchar(160), account_id integer UNIQUE
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='parent_account_fk') THEN
    ALTER TABLE public.parent ADD CONSTRAINT parent_account_fk FOREIGN KEY(account_id) REFERENCES public.account(id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.parent_student (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id integer NOT NULL REFERENCES public.parent(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.student(id) ON DELETE CASCADE,
  CONSTRAINT uq_parent_student UNIQUE(parent_id,student_id)
);

CREATE TABLE IF NOT EXISTS public.teacher_assignment (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id integer NOT NULL REFERENCES public.teacher(id) ON DELETE CASCADE,
  class_name varchar(10) NOT NULL, section varchar(10) NOT NULL DEFAULT '',
  CONSTRAINT uq_class_section_teacher UNIQUE(class_name,section)
);

CREATE TABLE IF NOT EXISTS public.report_card_config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id integer UNIQUE NOT NULL REFERENCES public.student(id) ON DELETE CASCADE,
  academic_session varchar(30) NOT NULL DEFAULT '2026-27', house varchar(80) DEFAULT '', class_teacher_name varchar(160) DEFAULT '',
  co_scholastic_json text DEFAULT '{}', discipline_json text DEFAULT '{}', health_json text DEFAULT '{}', remarks text DEFAULT '', principal_remarks text DEFAULT '',
  date_result varchar(80) DEFAULT '', next_academic_session varchar(30) DEFAULT '', session_begins varchar(40) DEFAULT '', summer_break_from varchar(40) DEFAULT '',
  school_reopens varchar(40) DEFAULT '', published boolean NOT NULL DEFAULT false, updated_by varchar(120) DEFAULT '', updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.subject (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code varchar(50) UNIQUE NOT NULL, name varchar(120) NOT NULL, class_band varchar(20) NOT NULL, language_group varchar(20), active boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS public.exam (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(50) UNIQUE NOT NULL, max_marks integer NOT NULL, order_index integer NOT NULL, is_final boolean NOT NULL DEFAULT false, active boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS public.mark (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id integer NOT NULL REFERENCES public.student(id) ON DELETE CASCADE, subject_code varchar(50) NOT NULL, exam_id integer NOT NULL REFERENCES public.exam(id) ON DELETE CASCADE, marks double precision, max_marks integer NOT NULL, updated_by varchar(120), updated_at timestamp NOT NULL DEFAULT now(), locked boolean NOT NULL DEFAULT false, CONSTRAINT uq_mark UNIQUE(student_id,subject_code,exam_id));
CREATE TABLE IF NOT EXISTS public.assessment_component (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id integer NOT NULL REFERENCES public.student(id) ON DELETE CASCADE, subject_code varchar(50) NOT NULL, multiple_assessment double precision DEFAULT 0, subject_enrichment double precision DEFAULT 0, portfolio double precision DEFAULT 0, internal_assessment double precision, annual_exam double precision, remarks varchar(500), CONSTRAINT uq_assessment_component UNIQUE(student_id,subject_code));

ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS source varchar(20);
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS marked_by varchar(120);
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS note varchar(500);
UPDATE public.attendance SET source=COALESCE(NULLIF(source,''),'manual') WHERE source IS NULL OR source='';
ALTER TABLE public.attendance ALTER COLUMN source SET DEFAULT 'manual';

CREATE TABLE IF NOT EXISTS public.announcement (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title varchar(180) NOT NULL, message text NOT NULL, audience varchar(30) NOT NULL DEFAULT 'all', published boolean NOT NULL DEFAULT false, created_by varchar(120) NOT NULL, created_at timestamp NOT NULL DEFAULT now(), published_at timestamp);
CREATE TABLE IF NOT EXISTS public.result_publication (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, exam_id integer NOT NULL REFERENCES public.exam(id) ON DELETE CASCADE, class_name varchar(10) NOT NULL, section varchar(10) NOT NULL DEFAULT '', published boolean NOT NULL DEFAULT false, published_at timestamp, published_by varchar(120), CONSTRAINT uq_result_publication UNIQUE(exam_id,class_name,section));
CREATE TABLE IF NOT EXISTS public.audit_event (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, occurred_at timestamp NOT NULL DEFAULT now(), actor_username varchar(120) NOT NULL, actor_role varchar(30) NOT NULL, action varchar(120) NOT NULL, target_type varchar(80), target_id varchar(80), ip_address varchar(64), user_agent text, metadata_json text, previous_hash varchar(64), event_hash varchar(64) NOT NULL);
CREATE TABLE IF NOT EXISTS public.school_setting (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, key varchar(120) UNIQUE NOT NULL, value text, updated_at timestamp NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.published_report (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id integer NOT NULL REFERENCES public.student(id) ON DELETE CASCADE, session_name varchar(30) NOT NULL, status varchar(20) NOT NULL DEFAULT 'draft', pdf_path varchar(255), published_at timestamp, published_by varchar(120), CONSTRAINT uq_published_report UNIQUE(student_id,session_name));
CREATE TABLE IF NOT EXISTS public.fee_invoice (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id integer NOT NULL REFERENCES public.student(id) ON DELETE CASCADE, title varchar(160) NOT NULL, amount_due double precision NOT NULL DEFAULT 0, due_date date, status varchar(20) NOT NULL DEFAULT 'pending', created_at timestamp NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.fee_payment (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, invoice_id integer NOT NULL REFERENCES public.fee_invoice(id) ON DELETE CASCADE, amount double precision NOT NULL, method varchar(40) NOT NULL DEFAULT 'offline', receipt_no varchar(80) UNIQUE NOT NULL, paid_at timestamp NOT NULL DEFAULT now(), received_by varchar(120));

CREATE TABLE IF NOT EXISTS public.school_clock (
  id integer PRIMARY KEY,
  override_time varchar(10),
  updated_at timestamp NOT NULL DEFAULT now()
);
INSERT INTO public.school_clock(id,override_time) VALUES (1,NULL) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.exam(name,max_marks,order_index,is_final) VALUES ('PT-1',40,1,false),('PT-2',80,2,false),('PT-3',40,3,false),('Final Examination',80,4,true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.school_setting(key,value) VALUES ('academic_session','2026-27') ON CONFLICT (key) DO NOTHING;

-- Convert legacy admin rows into the unified account table.
INSERT INTO public.account(username,password_hash,role,display_name,must_change_password,active,created_at,last_login)
SELECT a.username,a.password_hash,'admin','SCHOOL ADMINISTRATOR',false,true,a.created_at,a.last_login
FROM public.admin a
ON CONFLICT (username) DO NOTHING;

-- Convert legacy teacher logins and legacy student logins when usernames exist.
INSERT INTO public.account(username,password_hash,role,display_name,must_change_password,active,created_at,last_login)
SELECT t.username,t.password_hash,'teacher',t.name,false,COALESCE(t.active,true),t.created_at,t.last_login
FROM public.teacher t WHERE t.username IS NOT NULL
ON CONFLICT (username) DO NOTHING;

UPDATE public.teacher t SET account_id=a.id FROM public.account a WHERE a.username=t.username AND a.role='teacher' AND t.account_id IS NULL;
UPDATE public.student s SET face_encoding_json=s.face_encodings WHERE COALESCE(s.face_encoding_json,'')='' AND COALESCE(s.face_encodings,'')<>'';

CREATE INDEX IF NOT EXISTS ix_student_class_section ON public.student(class_name,section);
CREATE INDEX IF NOT EXISTS ix_attendance_date_status ON public.attendance(date,status);
CREATE INDEX IF NOT EXISTS ix_attendance_student_date ON public.attendance(student_id,date);
CREATE INDEX IF NOT EXISTS ix_announcement_audience_published ON public.announcement(audience,published);
CREATE INDEX IF NOT EXISTS ix_account_role ON public.account(role);

-- Keep the current schema available for manual rollback if needed.
