-- Render Testing 4 migration: teacher subject menus + fully configurable report-card labels
CREATE TABLE IF NOT EXISTS public.teacher_subject_assignment (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id integer NOT NULL REFERENCES public.teacher(id) ON DELETE CASCADE,
  subject_code varchar(50) NOT NULL,
  CONSTRAINT uq_teacher_subject_assignment UNIQUE(teacher_id,subject_code)
);
CREATE INDEX IF NOT EXISTS ix_teacher_subject_assignment_teacher ON public.teacher_subject_assignment(teacher_id);
ALTER TABLE public.report_card_config ADD COLUMN IF NOT EXISTS layout_json text DEFAULT '{}';
