-- V9 fee structure / automatic fee ledger
CREATE TABLE IF NOT EXISTS public.fee_structure (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_session varchar(30) NOT NULL,
  class_group varchar(80) NOT NULL,
  term_i double precision NOT NULL DEFAULT 0,
  term_ii double precision NOT NULL DEFAULT 0,
  term_iii double precision NOT NULL DEFAULT 0,
  term_iv double precision NOT NULL DEFAULT 0,
  total double precision NOT NULL DEFAULT 0,
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_by varchar(120) DEFAULT '',
  CONSTRAINT uq_fee_structure_session_group UNIQUE(academic_session,class_group)
);
CREATE INDEX IF NOT EXISTS ix_fee_structure_session ON public.fee_structure(academic_session);
CREATE TABLE IF NOT EXISTS public.fee_structure_document (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_session varchar(30) NOT NULL,
  filename varchar(255) NOT NULL,
  mimetype varchar(120) NOT NULL,
  file_data bytea NOT NULL,
  uploaded_at timestamp without time zone NOT NULL DEFAULT now(),
  uploaded_by varchar(120) DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ix_fee_structure_document_session ON public.fee_structure_document(academic_session);
ALTER TABLE public.fee_invoice ADD COLUMN IF NOT EXISTS academic_session varchar(30);
