CREATE TABLE IF NOT EXISTS public.fee_payment_window (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_session varchar(30) NOT NULL,
  term_key varchar(30) NOT NULL,
  term_label varchar(60) NOT NULL,
  payment_start date NOT NULL,
  payment_end date NOT NULL,
  fine_from date NOT NULL,
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_by varchar(120) DEFAULT '',
  CONSTRAINT uq_fee_payment_window_session_term UNIQUE (academic_session, term_key)
);
CREATE INDEX IF NOT EXISTS ix_fee_payment_window_session
ON public.fee_payment_window(academic_session, term_key);
INSERT INTO public.fee_payment_window
  (academic_session, term_key, term_label, payment_start, payment_end, fine_from, updated_by)
VALUES
  ('2026-27','term_i','1st Term','2026-04-16','2026-06-25','2026-06-26','system'),
  ('2026-27','term_ii','2nd Term','2026-07-01','2026-09-25','2026-09-26','system'),
  ('2026-27','term_iii','3rd Term','2026-10-01','2026-12-25','2026-12-26','system'),
  ('2026-27','term_iv','4th Term','2027-01-01','2027-02-20','2027-02-21','system')
ON CONFLICT (academic_session, term_key) DO UPDATE SET
  term_label=EXCLUDED.term_label,
  payment_start=EXCLUDED.payment_start,
  payment_end=EXCLUDED.payment_end,
  fine_from=EXCLUDED.fine_from;
